# Copyright (c) 2023 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============================================================================
ARG BASE_IMG=intel/xfastertransformer
ARG VERSION=dev-ubuntu22.04

FROM ${BASE_IMG}:${VERSION}

ARG USER_NAME
ARG USER_UID
ARG USER_GROUP
ARG USER_GID
ARG USER_PASSWD=qwer1234
ARG USER_HOME=/home/${USER_NAME}


############################# Set same user in container #############################
RUN apt-get install sudo -y
WORKDIR /
RUN getent group "${USER_GID}" || addgroup --force-badname --gid ${USER_GID} ${USER_GROUP}
RUN getent passwd "${USER_UID}" || adduser --force-badname --gid ${USER_GID} --uid ${USER_UID} \
      --disabled-password --home ${USER_HOME} --quiet ${USER_NAME}
RUN usermod -a -G sudo ${USER_NAME}
RUN echo "${USER_NAME} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/90-nopasswd-sudo

USER ${USER_UID}:${USER_GID}

RUN echo ${USER_NAME}:${USER_PASSWD} | sudo chpasswd
RUN whoami

# Set oneCCL environment
RUN echo "source /usr/local/oneCCL/env/setvars.sh" >> ${USER_HOME}/.bashrc
RUN echo 'export LD_LIBRARY_PATH=/usr/local/mklml_lnx_2019.0.5.20190502/lib:$LD_LIBRARY_PATH' >> ${USER_HOME}/.bashrc