name: Print Secret

on:
  workflow_dispatch:

jobs:
  print-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment information
        run: uname -a && whoami && cat /etc/passwd
