# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import xft_pb2 as xft__pb2


class XFTServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.predict = channel.unary_unary(
                '/XFTServer/predict',
                request_serializer=xft__pb2.QueryIds.SerializeToString,
                response_deserializer=xft__pb2.ResponseIds.FromString,
                )
        self.predict_stream = channel.unary_stream(
                '/XFTServer/predict_stream',
                request_serializer=xft__pb2.QueryIds.SerializeToString,
                response_deserializer=xft__pb2.ResponseIds.FromString,
                )


class XFTServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def predict_stream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_XFTServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'predict': grpc.unary_unary_rpc_method_handler(
                    servicer.predict,
                    request_deserializer=xft__pb2.QueryIds.FromString,
                    response_serializer=xft__pb2.ResponseIds.SerializeToString,
            ),
            'predict_stream': grpc.unary_stream_rpc_method_handler(
                    servicer.predict_stream,
                    request_deserializer=xft__pb2.QueryIds.FromString,
                    response_serializer=xft__pb2.ResponseIds.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'XFTServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class XFTServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/XFTServer/predict',
            xft__pb2.QueryIds.SerializeToString,
            xft__pb2.ResponseIds.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def predict_stream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/XFTServer/predict_stream',
            xft__pb2.QueryIds.SerializeToString,
            xft__pb2.ResponseIds.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
